# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: danielmeissler.Fabric
PackageVersion: 1.4.293
InstallerType: portable
Commands:
- fabric
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/tonymet/Fabric/releases/download/v1.4.294/fabric-windows-amd64.exe
  InstallerSha256: F1CDF850C5EA6C2DC1FAF33BD5F39D737E1656C3945C80C8A268B6F921A3720B
ManifestType: installer
ManifestVersion: 1.10.0
